### ISSUE TITLE
Plugin icons should allow guideline

### ISSUE THREAD

**Issue by Geno1024** [HMS-Core/hms-toolkit-convertor#3]
According to [IntelliJ Platform UI Guidelines -> Icons #12](https://jetbrains.github.io/ui/principles/icons/#12), icons should be aligned in pixels.

But, in the [docs of this plugin](https://developer.huawei.com/consumer/en/doc/development/Tools-Guides/90419706), there is a screenshot [showing a menu of this plugin](https://communityfile-drcn.op.hicloud.com/FileServer/getFile/cmtyPub/011/111/111/0000000000011111111.20200311190238.19236678006321655699414327501952:50510609065436:2800:A605BA8CF1E83E25EC4586656A2A85A9E18345D258D55256DCBDBECB16D1AC16.png?needInitFileName=true?needInitFileName=true), with blurred borders, pixels, etc.

Hope to fix that.

**Comment by Geno1024** [comment]
According to [IntelliJ Platform UI Guidelines -> Icons #35](https://jetbrains.github.io/ui/principles/icons/#35), the images should be `.svg` instead of [`.png`](https://github.com/HMS-Core/hms-toolkit-convertor/tree/master/src/IDE/convertor-idea/src/main/resources/icons).

**Comment by big-surprise** [comment]
We will deal with this matter shortly, thank you
