### ISSUE TITLE
Converter generated code is full of "Not Supported" exceptions

### ISSUE THREAD

**Issue by mykola-dev** [HMS-Core/hms-toolkit-convertor#32]
**Description**
I'm trying to convert existing project which actively uses GMS services to HMS with the Converter tool.
It seems works, but my generated code looks like this:

```
  public org.xms.g.tasks.Task<org.xms.f.remoteconfig.ExtensionRemoteConfigInfo> ensureInitialized() {
        throw new java.lang.RuntimeException("Not Supported");
    }
    
    public org.xms.g.tasks.Task<java.lang.Void> fetch(long param0) {
        throw new java.lang.RuntimeException("Not Supported");
    }
    
    public org.xms.g.tasks.Task<java.lang.Void> fetch() {
        throw new java.lang.RuntimeException("Not Supported");
    }
    
    public org.xms.g.tasks.Task<java.lang.Boolean> fetchAndActivate() {
        throw new java.lang.RuntimeException("Not Supported");
    }
```

I see lot of same stubs over the whole `xmsadapter` module. So now when I run my app it crashes when uses one of these methods.

**Expected behavior**
The converter should support full migration, or at least should mark unsupported methods as "need to be manually converted"

**Current behavior**
The converter marks GMS apis as "auto convertible" but the generated code isn't usable.

**Environment**
 - Platform: native Android
 - Architecture: arm-v7a, armv7
 - OS Version Android 4.4 - 11
 - Source branch: installed from Intellij marketplace
 - Android Studio version: 4.1

**Comment by wayne1929** [comment]
Can you take a screenshot? The effect we see here is 
![image](https://user-images.githubusercontent.com/4608468/107029444-fc211700-67e9-11eb-89be-da4bbb93f18f.png)
then you can click the link [Detail](https://developer.huawei.com/consumer/en/doc/development/Tools-Guides/agc-conversion-remote-0000001050157274)

**Comment by mykola-dev** [comment]
I'm talking about the "Auto" segment. It converts my code and imports, by replacing e.g. FirebaseMessaging by ExtensionMessaging etc. But ExtensionMessaging class is full of "not supported" methods

**Comment by wayne1929** [comment]
Now，some classes and methods are "not supported". but some "not support" methods are provided with manual conversion instructions to help solve them. eg FirebaseMessaging by ExtensionMessaging's manual conversion guide is [https://developer.huawei.com/consumer/en/doc/development/Tools-Guides/push-conversion-0000001050060304#EN-US_TOPIC_0000001050060304__section167749454350](url). I hope this can help you!
